### ISSUE TITLE
Update Travis CI to run static analysis in each pull request

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#79]
As a developer, I would like to augment the current development environment to run static analysis on every pull request as well as improve upon the current pipeline's stages. 

- [x] Integration of Static Analysis Tool @jadmalek 1 point
- [x] Running/testing of analysis on pull request @sophiaquach16 1 point
- [x] Test coverage for Sprint 5 @jadmalek 0.5 points
- [x] Test coverage for Sprint 6 @sophiaquach16 0.5 points 

[Story Points: 3 points] - @jadmalek 1.5 points & @sophiaquach16 1.5 points
[Risk: Low] - for all tasks
[Priority: High] - for all tasks

**Comment by amawai** [comment]
Closed by #111
